trigger:
  - main

pool:
  name: Default
  demands:
    - agent.name -equals Linux-Mint

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'

  - script: npm ci
    workingDirectory: Playwright_Project_1
    displayName: Install dependencies

  #- script: npx playwright install --with-deps
  #  workingDirectory: Playwright_Project_1
  #  displayName: Install Playwright browsers

  - script: npx playwright test
    workingDirectory: Playwright_Project_1
    displayName: Run Playwright tests

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: Playwright_Project_1/test-results/*.xml

  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: Playwright_Project_1/playwright-report
      artifact: playwright-report